default:
  port: 3000
  cache_assets: true
  merchant_id: 375917
  secret_key: SAIPPUAKAUPPIAS
  api_payment:
    url: https://payment.checkout.fi
    strictSSL: true
  api_refund:
    url: https://rpcapi.checkout.dev/refund2
    strictSSL: true

development:
  cache_assets: false

production: &production
  port: #{process.env.PORT}
